# Generated by Django 2.1.1 on 2018-09-17 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.CharField(db_index=True, max_length=30, primary_key=True, serialize=False, unique=True)),
                ('author', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=256)),
                ('content', models.TextField()),
                ('published', models.DateTimeField()),
                ('ip', models.GenericIPAddressField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('published', models.DateTimeField()),
                ('ip', models.GenericIPAddressField()),
                ('tag', models.CharField(choices=[('PUSH', 'push'), ('NEUTRAL', 'neutral'), ('BOO', 'boo')], max_length=10)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userdata.Article')),
            ],
        ),
    ]
